[tool.poetry]
name = "dtocean-hydrodynamics"
version = "3.3.6"
description = "Hydrodynamics module for the DTOcean tools"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/DTOcean/dtocean"
homepage = "https://dtocean.github.io/dtocean"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux"
]
packages = [
  {include = "dtocean_hydro", from="src"},
  {include = "dtocean_plugins", from="src"},
  {include = "dtocean_tidal", from="src"},
  {include = "dtocean_wave", from="src"},
  {include = "dtocean_wec", from="src"},
  ]
exclude = [
  "src/dtocean_plugins/strategy_guis/.gitignore",
  "src/dtocean_plugins/strategy_guis/*.ui",
  "src/dtocean_tidal/submodel/ParametricWake/read_db.f90",
  "src/dtocean_wec/designer/.gitignore",
  "src/dtocean_wec/designer/*.ui"
]
include = [
    { path = "meson.build", format = "sdist" },
    { path = "src/dtocean_plugins/strategy_guis/*.ui", format = "sdist" },
    { path = "src/dtocean_plugins/strategy_guis/ui_*.py", format = "wheel" },
    { path = "src/dtocean_tidal/submodel/ParametricWake/read_db.f90", format = "sdist" },
    { path = "src/dtocean_tidal/submodel/ParametricWake/*.so", format = "wheel" },
    { path = "src/dtocean_tidal/submodel/ParametricWake/*.pyd", format = "wheel"},
    { path = "src/dtocean_tidal/submodel/ParametricWake/*.dll", format = "wheel"},
    { path = "src/dtocean_tidal/submodel/ParametricWake/*.dll.a", format = "wheel"},
    { path = "src/dtocean_wec/designer/*.ui", format = "sdist" },
    { path = "src/dtocean_wec/designer/ui_*.py", format = "wheel"},
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/DTOcean/dtocean/issues"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
cma = "^4.4.1"
h5py = "^3.12.1"
matplotlib = "^3.10.8"
natsort = "^8.4.0"
numpy = "^2.3.5"
pandas = "^2.2.3"
pyopengl = "^3.1.7"
scikit-learn = "^1.6.0"
scipy = "^1.14.1"
shapely = "^2.0.6"
polite-config = {path = "../polite-config", develop = true}
contourpy = "^1.3.1"
pyside6 = "^6.9.0"
shiboken6 = "^6.9.0"
pillow = "^11.2.1"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
mock = "^5.1.0"
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
pytest-qt = "^4.5.0"
pytest-cov = "^6.0.0"

[tool.poetry.group.test-extras]
optional = true

[tool.poetry.group.test-extras.dependencies]
dtocean-app = {path = "../dtocean-app", develop = true}

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
ruff = "^0.8.3"
pyright = "^1.1.396"
deptry = "^0.21.1"
pandas-stubs = "^2.2.3.241126"

[tool.poetry.scripts]
dtocean-hydro = 'dtocean_hydro._cli:run'
dtocean-wec = 'dtocean_wec:gui_interface'

[tool.poetry.build]
script = "scripts/build-extension.py"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '^'

[tool.pytest.ini_options]
filterwarnings = [
    'ignore:numpy.ndarray size changed:RuntimeWarning',
]

[tool.pyright]
typeCheckingMode = "basic"
exclude = [
  "src/dtocean_wec/designer/ui_*.py",
  "src/dtocean_plugins/strategy_guis/ui_*.py"
]

[tool.ruff]
line-length = 80

[tool.semantic_release]
commit_parser = "../../scripts/dtocean_commit_parser.py:DTOceanCommitParser"
commit_message = """\
chore(release): dtocean-hydrodynamics@{version}

Automatically generated by python-semantic-release
"""
tag_format = "dtocean-hydrodynamics-v{version}"
version_toml = ["pyproject.toml:tool.poetry.version"]

[tool.semantic_release.branches.main]
match = "(main)"

[tool.semantic_release.changelog]
# Recommended patterns for conventional commits parser that is scope aware
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Initial [Cc]ommit.*'''
]

[tool.semantic_release.commit_parser_options]
scope_prefix = "dtocean-hydrodynamics"

[tool.semantic_release.commit_parser_options.path_filters.main]
paths = ["."]

[tool.semantic_release.commit_parser_options.path_filters.polite-config]
paths = ["../polite-config"]
max_bump_level = 2
trigger_bump_level = 4

[build-system]
requires = ["poetry-core", "meson", "ninja", "numpy~=2.3.5", "pyside6"]
build-backend = "poetry.core.masonry.api"
