[project]
name = "dtocean-qt"
version = "1.1.5"
description = "Qt extensions for the DTOcean GUI"
authors = [
    { name = "The DTOcean Developers"},
]
maintainers = [
    { name = "Mathew Topper", email = "damm_horse@yahoo.co.uk" },
]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux"
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "chardet (>=5.2.0,<6.0.0)",
    "pyside6 (>=6.9.0,<7.0.0)",
    "easygui (>=0.98.3,<0.99.0)",
    "numpy (>=2.3.5,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)"
]

[project.urls]
homepage = "https://python-poetry.org/"
repository = "https://github.com/DTOcean/dtocean"
issues = "https://github.com/DTOcean/dtocean/issues"

[tool.poetry]
exclude = [
  'src/dtocean_qt/pandas/views/_ui/icons.qrc',
  'src/dtocean_qt/pandas/views/_ui/icons/',
  'src/dtocean_qt/pandas/views/_ui/*.ui',
]
include = [
  'src/dtocean_qt/pandas/views/_ui/icons.qrc',
  'src/dtocean_qt/pandas/views/_ui/icons/',
  'src/dtocean_qt/pandas/views/_ui/*.ui',
  { path = 'src/dtocean_qt/pandas/views/_ui/icons_rc.py', format = "wheel" },
]

[tool.poetry.build]
script = "scripts/build-icons.py"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-qt = "^4.5.0"
pytest-cov = "^6.0.0"
pytest-env = "^1.1.5"

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
ruff = "^0.8.3"
pyright = "^1.1.396"
deptry = "^0.21.1"
pandas-stubs = "^2.2.3.241126"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '^'

[tool.pyright]
typeCheckingMode = "basic"

[tool.pytest.ini_options]
filterwarnings = [
    'ignore:Failed to disconnect *:RuntimeWarning',
]

[tool.pytest_env]
QT_DEBUG_PLUGINS = 1

[tool.ruff]
line-length = 80

[tool.semantic_release]
commit_parser = "../../scripts/dtocean_commit_parser.py:DTOceanCommitParser"
commit_message = """\
chore(release): dtocean-qt@{version}

Automatically generated by python-semantic-release
"""
tag_format = "dtocean-qt-v{version}"
version_toml = ["pyproject.toml:project.version"]

[tool.semantic_release.branches.main]
match = "(main)"

[tool.semantic_release.changelog]
# Recommended patterns for conventional commits parser that is scope aware
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Initial [Cc]ommit.*''',
]

[tool.semantic_release.commit_parser_options]
scope_prefix = "dtocean-qt"

[tool.semantic_release.commit_parser_options.path_filters.main]
paths = ["."]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "pyside6"]
build-backend = "poetry.core.masonry.api"
