[tool.poetry]
name = "dtocean-app"
version = "2.1.5"
description = "Main graphical application for the DTOcean tools"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
readme = "README.md"
packages = [
  {include = "dtocean_app", from="src"},
  {include = "dtocean_plugins", from="src"},
]
include = [
  { path = "designer", format = ["sdist"] },
  { path = 'src/dtocean_app/designer/**/*.py', format = "wheel" },
]

[tool.poetry.build]
script = "scripts/build-widgets.py"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
dtocean-core = {path = "../dtocean-core", develop = true}
dtocean-qt = {path = "../dtocean-qt", develop = true}
mdo-engine = {path = "../mdo-engine", develop = true}
polite-config = {path = "../polite-config", develop = true}
matplotlib = "^3.10.8"
numpy = "^2.3.5"
pandas = ">=2.2.3,<3.0.0"
shiboken6 = "^6.9.0"
pyside6 = "^6.9.0"
pillow = "^11.2.1"
pywin32 = {version = "^308", platform = "win32"}
pyshortcuts = "^1.9.7"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
mock = "^5.1.0"
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
pytest-qt = "^4.5.0"
pytest-cov = "^6.0.0"

[tool.poetry.group.test-extras]
optional = true

[tool.poetry.group.test-extras.dependencies]
dtocean = {path = "../dtocean", develop = true}
dtocean-docs = {path = "../dtocean-docs", develop = true}

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
ruff = "^0.8.3"
pyright = "^1.1.396"
deptry = "^0.21.1"
pandas-stubs = "^2.2.3.241126"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '^'

[tool.pyright]
typeCheckingMode = "basic"
"exclude" = [
  "src/dtocean_app/designer/**"
]

[tool.ruff]
line-length = 80

[tool.semantic_release]
commit_parser = "../../scripts/dtocean_commit_parser.py:DTOceanCommitParser"
commit_message = """\
chore(release): dtocean-app@{version}

Automatically generated by python-semantic-release
"""
tag_format = "dtocean-app-v{version}"
version_toml = ["pyproject.toml:tool.poetry.version"]

[tool.semantic_release.branches.main]
match = "(main)"

[tool.semantic_release.changelog]
# Recommended patterns for conventional commits parser that is scope aware
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Initial [Cc]ommit.*'''
]

[tool.semantic_release.commit_parser_options]
scope_prefix = "dtocean-app"

[tool.semantic_release.commit_parser_options.path_filters.main]
paths = ["."]

[tool.semantic_release.commit_parser_options.path_filters.polite-config]
paths = ["../polite-config"]
max_bump_level = 2
trigger_bump_level = 4

[tool.semantic_release.commit_parser_options.path_filters.mdo-engine]
paths = ["../mdo-engine"]
max_bump_level = 2
trigger_bump_level = 4

[tool.semantic_release.commit_parser_options.path_filters.dtocean-core]
paths = ["../dtocean-core"]
max_bump_level = 2
trigger_bump_level = 4

[tool.semantic_release.commit_parser_options.path_filters.dtocean-qt]
paths = ["../dtocean-qt"]
max_bump_level = 2
trigger_bump_level = 4

[build-system]
requires = ["poetry-core", "pyside6"]
build-backend = "poetry.core.masonry.api"
