[project]
name = "dtocean-docs"
version = "0.1.0"
description = "Offline DTOcean documentation for dtocean-app"
authors = [{ name = "Mathew Topper", email = "damm_horse@yahoo.co.uk" }]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = []

[tool.poetry]
packages = [{ include = "dtocean_docs", from = "src" }]
include = [
    { path = "src/dtocean_docs/html", format = ["sdist", "wheel"] }
]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
ruff = "^0.8.3"
pyright = "^1.1.396"

[tool.poetry.build]
script = "scripts/build-docs.py"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '=='

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 80

[build-system]
requires = [
    "poetry-core>=2.0.0,<3.0.0",
    "sphinx-multiversion @ git+https://github.com/sphinx-contrib/multiversion.git",
    "sphinx-rtd-theme",
]
build-backend = "poetry.core.masonry.api"
