[tool.poetry]
name = "mdo-engine"
version = "1.0.6"
description = "Data management, coupling and execution for MDO problems"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
license = "MIT"
readme = "README.md"
packages = [{include = "mdo_engine", from="src"}]
include = ['test/data/yaml/*.yaml']

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
openpyxl = "^3.1.5"
pandas = "^2.2.3"
pyyaml = "^6.0.2"
sqlalchemy = "^2.0.36"
xlrd = "^2.0.1"
xlwt = "^1.3.0"
polite-config = {path = "../polite-config", develop = true}
python-box = "^7.2.0"
pandas-stubs = "^2.2.3.241126"
psycopg = {extras = ["binary"], version = "^3.2.6"}
geoalchemy2 = "^0.17.1"
shapely = "^2.0.7"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
mock = "^5.1.0"
dtocean-dummy-module = {path = "../dtocean-dummy-module"}
pytest-cov = "^6.0.0"
pytest-postgresql = "^7.0.2"

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
ruff = "^0.8.3"
pyright = "^1.1.395"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '^'

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 80

[tool.semantic_release]
commit_parser = "../../scripts/dtocean_commit_parser.py:DTOceanCommitParser"
commit_message = """\
chore(release): mdo-engine@{version}

Automatically generated by python-semantic-release
"""
tag_format = "mdo-engine-v{version}"
version_toml = ["pyproject.toml:tool.poetry.version"]

[tool.semantic_release.branches.main]
match = "(main)"

[tool.semantic_release.changelog]
# Recommended patterns for conventional commits parser that is scope aware
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Initial [Cc]ommit.*'''
]

[tool.semantic_release.commit_parser_options]
scope_prefix = "mdo-engine"

[tool.semantic_release.commit_parser_options.path_filters.main]
paths = ["."]

[tool.semantic_release.commit_parser_options.path_filters.polite-config]
paths = ["../polite-config"]
max_bump_level = 2
trigger_bump_level = 4

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
