[tool.poetry]
name = "dtocean-core"
version = "3.1.1"
description = "The main (non-graphical) interface for the DTOcean tools"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [
  { include = "dtocean_core", from = "src" },
  { include = "dtocean_plugins", from = "src"},
]
include = [
  { path = 'src/dtocean_core/data/yaml/*.yaml', format = ["sdist", "wheel"] },
  { path = 'src/dtocean_core/config/*.ini', format = ["sdist", "wheel"] },
  { path = 'src/dtocean_core/config/*.yaml', format = ["sdist", "wheel"] },
  { path = 'src/dtocean_core/strategies/position_optimiser/*.yaml', format = ["sdist", "wheel"] },
]

[tool.poetry.scripts]
dtocean = 'dtocean_core.utils.cli:main'
_dtocean-optim-pos = 'dtocean_plugins.strategies.position_optimiser.iterator:interface'

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
mdo-engine = {path = "../mdo-engine", develop = true}
polite-config = {path = "../polite-config", develop = true}
cma = "^4.4.1"
cycler = "^0.12.1"
geoalchemy2 = "^0.17.1"
matplotlib = "^3.10.8"
natsort = "^8.4.0"
netcdf4 = "^1.7.2"
numpy = "^2.3.5"
openpyxl = "^3.1.5"
pandas = "^2.2.3"
pillow = "^11.0.0"
pyproj = "^3.6.1"
pyshp = "^2.3.1"
python-dateutil = "^2.9.0.post0"
pyyaml = "^6.0.2"
ruamel-yaml-clib = "^0.2.12"
ruamel-yaml = "^0.18.6"
scipy = "^1.17.0"
shapely = "^2.0.6"
utm = "^0.7.0"
xarray = "^2024.11.0"
xlrd = "^2.0.1"
basemap = "^2.0.0"
pywin32 = {version = "^308", platform = "win32"}
cmocean = "^4.0.3"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
mock = "^5.1.0"
pytest-cov = "^6.0.0"
pytest-postgresql = "^7.0.1"
pytz = "^2025.2"

[tool.poetry.group.test-extras]
optional = true

[tool.poetry.group.test-extras.dependencies]
dtocean-app = {path = "../dtocean-app", develop = true}

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
ruff = "^0.8.3"
pyright = "^1.1.395"
deptry = "^0.21.1"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '^'

[tool.pytest.ini_options]
filterwarnings = [
    'ignore:numpy.ndarray size changed:RuntimeWarning',
]
qt_api="pyside6"

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 80

[tool.semantic_release]
commit_parser = "../../scripts/dtocean_commit_parser.py:DTOceanCommitParser"
commit_message = """\
chore(release): dtocean-core@{version}

Automatically generated by python-semantic-release
"""
tag_format = "dtocean-core-v{version}"
version_toml = ["pyproject.toml:tool.poetry.version"]

[tool.semantic_release.branches.main]
match = "(main)"

[tool.semantic_release.changelog]
# Recommended patterns for conventional commits parser that is scope aware
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Initial [Cc]ommit.*'''
]

[tool.semantic_release.commit_parser_options]
scope_prefix = "dtocean-core"

[tool.semantic_release.commit_parser_options.path_filters.main]
paths = ["."]

[tool.semantic_release.commit_parser_options.path_filters.mdo-engine]
paths = ["../mdo-engine"]
max_bump_level = 2
trigger_bump_level = 4

[tool.semantic_release.commit_parser_options.path_filters.polite-config]
paths = ["../polite-config"]
max_bump_level = 2
trigger_bump_level = 4

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
