[tool.poetry]
name = "dtocean-dummy-module"
version = "1.0.0"
description = "Dummy DTOcean module used in mdo-engine tests"
authors = ["The DTOcean Developers"]
maintainers = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/DTOcean/dtocean"
homepage = "https://dtocean.github.io/dtocean"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux"
]
packages = [{include = "dtocean_dummy", from="src"}]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/DTOcean/dtocean/issues"

[tool.poetry.scripts]
dtocean-dummy = 'dtocean_dummy.command:module_interface'

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.3.5"
pandas = "^2.2.3"
openpyxl = "^3.1.5"
xlrd = "^2.0.1"
xlwt = "^1.3.0"
polite-config = {path = "../polite-config", develop = true}

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
pyright = "^1.1.390"
ruff = "^0.8.3"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '~'

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
