name: dtocean-app actions
on:
  push:
    branches: [ next ]
    paths:
      - '.codecov.yml'
      - '.github/workflows/dtocean-app.yml'
      - 'packages/dtocean-app/**'
      - 'packages/dtocean-core/**'
      - 'packages/dtocean-qt/**'
      - 'packages/mdo-engine/**'
      - 'packages/polite-config/**'
  pull_request:
    branches: [ next ]
    paths:
      - '.codecov.yml'
      - '.github/workflows/dtocean-app.yml'
      - 'packages/dtocean-app/**'
      - 'packages/dtocean-core/**'
      - 'packages/dtocean-qt/**'
      - 'packages/mdo-engine/**'
      - 'packages/polite-config/**'
jobs:
  pytest:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    defaults:
      run:
        working-directory: packages/dtocean-app
    env:
      DISPLAY: ':99.0'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      # https://github.com/actions/runner-images/issues/7048
      - name: Change Mirror Priorities (Linux)
        run: |
          sudo sed -i '/archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:2/priority:0/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/azure.archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:0/priority:1/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/security.ubuntu.com\/ubuntu\/\tpriority/ s/priority:3/priority:2/' /etc/apt/apt-mirrors.txt
          sudo cat /etc/apt/apt-mirrors.txt
        if: runner.os == 'Linux'
      - name: Install additional libraries (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libxkbcommon-x11-0 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 x11-utils
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
        if: runner.os == 'Linux'
      - name: Install dtocean-app
        uses: ./.github/actions/poetry-install
        with: 
          root-directory: ${{ github.workspace }}/packages/dtocean-app
          groups: '["test"]'
      - name: Run tests
        run: |
          poetry run pytest -v --cov=src --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: dtocean-app
  audit:
    name: Code audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/dtocean-app
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install package
        run: |
          poetry install --with audit
      - name: Run ruff
        run: |
          poetry run ruff check --output-format github
      - name: Run pyright
        run: |
          poetry run pyright src
