name: dtocean-dummy-module tests
on:
  push:
    branches: [ next ]
    paths:
      - '.codecov.yml'
      - '.github/workflows/test-dtocean-dummy-module.yml'
      - 'packages/dtocean-dummy-module/**'
      - 'packages/polite-config/**'
      - 'poetry.lock'
  pull_request:
    branches: [ next ]
    paths:
      - '.codecov.yml'
      - '.github/workflows/test-dtocean-dummy-module.yml'
      - 'packages/dtocean-dummy-module/**'
      - 'packages/polite-config/**'
      - 'poetry.lock'

jobs:
  pytest:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    defaults:
      run:
        working-directory: packages/dtocean-dummy-module
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install poetry-monoranger-plugin
        run: |
          poetry self add poetry-monoranger-plugin
      - name: Install package
        run: |
          poetry install --only dtocean-dummy-module,test
      - name: Run tests
        run: |
          poetry run pytest --cov src --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: dtocean-dummy-module
  audit:
    name: Code audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/dtocean-dummy-module
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install poetry-monoranger-plugin
        run: |
          poetry self add poetry-monoranger-plugin
      - name: Install package
        run: |
          poetry install --only audit,dtocean-dummy-module
      - name: Run ruff
        run: |
          poetry run ruff check --output-format github
      - name: Run pyright
        run: |
          poetry run pyright src
