name: dtocean-core tests
on:
  push:
    branches: [ next ]
    paths:
      - '.codecov.yml'
      - '.github/workflows/test-dtocean-core.yml'
      - 'packages/dtocean-app/src/**'
      - 'packages/dtocean-core/**'
      - 'packages/mdo-engine/src/**'
      - 'packages/polite-config/src/**'
      - 'poetry.lock'
  pull_request:
    branches: [ next ]
    paths:
      - '.codecov.yml'
      - '.github/workflows/test-dtocean-core.yml'
      - 'packages/dtocean-app/src/**'
      - 'packages/dtocean-core/**'
      - 'packages/mdo-engine/src/**'
      - 'packages/polite-config/src/**'
      - 'poetry.lock'

jobs:
  pytest-linux:
    name: Unit tests (ubuntu-latest)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/dtocean-core
    env:
      DATABASE_URL: https://github.com/DTOcean/dtocean-database-next/releases/download/v2026.01.0/dtocean-database-v2026.01.0.tar.gz
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      # https://github.com/actions/runner-images/issues/7048
      - name: Change mirror priorities
        run: |
          sudo sed -i '/archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:2/priority:0/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/azure.archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:0/priority:1/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/security.ubuntu.com\/ubuntu\/\tpriority/ s/priority:3/priority:2/' /etc/apt/apt-mirrors.txt
          sudo cat /etc/apt/apt-mirrors.txt
      - name: Install system dependencies (GUI)
        run: sudo apt update && sudo apt-get install -y libegl1-mesa-dev
      - name: Set database root password
        run: |
          echo "POSTGRES_PASSWORD=$(uuidgen)" >> $GITHUB_ENV
      - name: Cache database folder
        uses: actions/cache@v4
        id: cache
        with:
          path: database
          key: ${{ env.DATABASE_URL }}
      - name: Download and extract database folder
        run: |
          mkdir database
          wget -O dtocean-database.tar.gz ${DATABASE_URL}
          tar xzf dtocean-database.tar.gz -C database
        working-directory: ${{ github.workspace }}
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Start database container
        run: |
          docker run \
          --name dtocean-database \
          --mount type=bind,src=${GITHUB_WORKSPACE}/database/export,dst=/home/postgres/export \
          -e POSTGRES_PASSWORD \
          -p 5432:5432 \
          -d \
          postgis/postgis
      - name: Install package
        uses: ./.github/actions/poetry-install
        with: 
          groups: '["dtocean-app", "dtocean-core", "test", "test-postgresql"]'
      - name: Run tests
        run: |
          poetry run pytest --cov=src --cov-report=xml --postgresql-password="${POSTGRES_PASSWORD}" --postgresql-path=${GITHUB_WORKSPACE}/database tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: dtocean-core
      - name: Stop database container
        run: docker stop dtocean-database
  pytest-windows:
    name: Unit tests (windows-latest)
    runs-on: windows-latest
    defaults:
      run:
        working-directory: packages/dtocean-core
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      - name: Install package
        uses: ./.github/actions/poetry-install
        with: 
          groups: '["dtocean-app", "dtocean-core", "test"]'
      - name: Run tests
        run: |
          poetry run pytest --cov=src --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: dtocean-core
  audit:
    name: Code audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/dtocean-core
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install package
        uses: ./.github/actions/poetry-install
        with: 
          groups: '["audit", "dtocean-app", "dtocean-core"]'
      - name: Run ruff
        run: |
          poetry run ruff check --output-format github
      - name: Run pyright
        run: |
          poetry run pyright src
